### ISSUE TITLE
Support redub test

### ISSUE THREAD

**Issue by nordlow** [MrcSnm/redub#10]
Doing `redub test` in, for instance, https://gitlab.com/per.nordlow/gmp-d fails as

```
Dependencies resolved in 6 ms for "debug" using dmd
Project gmp-d is fully parallelizable! Will build everything at the same time
Up-to-Date: gmp-d  []. Took 0ms
Up-to-Date: gmp-d, skipping linking
Built project in 0 ms.
Error Program exited with code 1
```

. Supporting this would be great.

**Comment by MrcSnm** [comment]
This is a little out of scope from what I wanted to use this project, I've done a plenty of work, but this is also not hard to support, if anyone want to do it, I can accept the PR.

**Comment by MrcSnm** [comment]
Well I ended up implementing that, so, that one is closed now

**Comment by nordlow** [comment]
Wonderful!
