### ISSUE TITLE
Problems building and other things

### ISSUE THREAD

**Issue by Kapendev** [MrcSnm/redub#12]
I wanted to try redub, but I had some problems with it.
Some info about my setup:
* OS:  Ubuntu Studio 23.10
* DMD64 D Compiler v2.107.0
* LDC 1.30.0 based on DMD v2.100.1 and LLVM 14.0.6

So:
1. I cloned the repo and run `dub -b debug-release --compiler=ldc2` but I get this error message: `Unknown build type for redub: 'debug-release'`. Building with `dub build` seems to work.
2. I can build redub with redub but I can't build my project with redub. I get this error message: `core.exception.RangeError@/home/alex/Documents/redub/source/redub/parsers/environment.d(259): Range violation`. My project depends on one library. I also put that library inside my project's source folder but I had the same error.

For some extra info about 2, the library that I use with my project is [this](https://github.com/Kapendev/popka) one.

**Comment by MrcSnm** [comment]
Oh sorry the first flag I put it wrong. It should be `release-debug` instead of `debug-release` .

I'll try to get into point 2 asap too

**Comment by MrcSnm** [comment]
I wasn't able to reproduce this issue on Windows. This looks like very strange. I'll have to take a look in unbuntu

**Comment by MrcSnm** [comment]
redub's  redub/source/redub/parsers/environment.d(259) with imported!"std.stdio".writeln("Return: ", ret, " [Start: ", outStart, "] Source: ", str, " [Start: ", srcStart, "]");, build it and test against your project then send me what it shows?

**Comment by MrcSnm** [comment]
Fixed:

The problem was that the parser was failing in some situations when trying to escape `$`.

Test Case Added:
```d
    assert(parseStringWithEnvironment("$$ORIGIN") == "$ORIGIN");
```
