### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by oracle1wr** [MrcSnm/redub#16]
error message:
hipjson/source/hipjson.d(175,50): Error: found `T` when expecting `)`
hipjson/source/hipjson.d(175,51): Error: found `)` when expecting `;`
hipjson/source/hipjson.d(175,52): Deprecation: use `{ }` for an empty statement, not `;`
Error ldc2 failed with exit code 1.

Branch:
**main**

Compiler:
LDC - the LLVM D compiler (1.30.0)
DMD64 D Compiler v2.102.2

Command: 
dub build -b release-debug --compiler=ldc2

Can you please advice what is going on. Is there are any compiler version limitation?

**Comment by MrcSnm** [comment]
Yeah so your compiler looks very old, so, it might have been a version which T didn't turn into T.stringof automatically.
I could try simply using .stringof since this could increase some compiler versions support
