### ISSUE TITLE
Target path from the command line

### ISSUE THREAD

**Issue by 0xEAB** [MrcSnm/redub#21]
Is it possible with redub to specify a target path on the command line?

Use case: `redub build --target-path="/usr/bin/app-name"`
So one can have a deterministic target-path – even if the project recipe changes.

Classic DUB feature request: https://github.com/dlang/dub/issues/902

**Comment by MrcSnm** [comment]
Isn't that feature request actually `dub build --root=`

**Comment by MrcSnm** [comment]
Implemented `--targetPath` and `--targetName` flags, while keeping it optimized for using cache on same build types :)

**Comment by 0xEAB** [comment]
You absolutely rock :metal:
