### ISSUE TITLE
redub fails if sources are not in source despite sourcePaths being set

### ISSUE THREAD

**Issue by o3o** [MrcSnm/redub#23]
As shown [here](https://github.com/o3o/redub-issue23), redub generates errors if the source files are not located in the source directory, even though `sourcePaths` is specified in the configuration. On the other hand, dub works correctly with this configuration.
## Steps to Reproduce:
```
> git clone https://github.com/o3o/redub-issue23.git
> cd rebub-issue23
> redub build

Build Failure: 'rname  []'
	Redub v1.13.5
	dmd 2.109.1
	Failed with flags:

	
Failed after 3ms with message
	object.Exception@source/redub/command_generators/commons.d(298):
	File was specified twice: File '/home/o3o/d/workshop/redub-issue/app.d' was specified in sourceFiles at directory '/home/o3o/d/workshop/redub-issue'. But it can already be found based on the current sourcePaths: ["/home/o3o/d/workshop/redub-issue"].  Either add this file to excludeSourceFiles or remove it from sourceFiles.
----------------
source/redub/command_generators/commons.d:298 [0x5b732926c0a6]
source/redub/command_generators/d_compilers.d:55 [0x5b732926d653]
source/redub/command_generators/automatic.d [0x5b73292733a9]
source/redub/building/compile.d:372 [0x5b732927a91a]
source/redub/api.d:196 [0x5b7329288706]
source/redub/api.d:108 [0x5b73292881b0]
source/app.d:207 [0x5b732928b940]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7a91c35aa06c]
??:? _d_run_main2 [0x7a91c35a9e86]
??:? _d_run_main [0x7a91c35a9cdc]
??:? [0x7a91c3208e07]
??:? __libc_start_main [0x7a91c3208ecb]
??:? [0x5b73292253d4]
Warning: If you think this is a bug on redub, do test with dub, if it works, do file an issue at https://github.com/MrcSnm/redub/issues/new/choose
object.Exception@source/redub/api.d(203): Build failure
----------------
source/redub/api.d [0x5b73292883a0]
source/app.d:207 [0x5b732928b940]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7a91c35aa06c]
??:? _d_run_main2 [0x7a91c35a9e86]
??:? _d_run_main [0x7a91c35a9cdc]
??:? [0x7a91c3208e07]
??:? __libc_start_main [0x7a91c3208ecb]
??:? [0x5b73292253d4]

```
If I remove `sourcePaths`
```
Build Failure: 'rname  []'
	Redub v1.13.5
	dmd 2.109.1
	Failed with flags:

	/usr/bin/dmd '-color=on' -op '-od=/home/o3o/.dub/.redub/302574E9E172D1EA/obj' -debug -g '-version=Have_rname' /home/o3o/d/workshop/redub-issue/app.d -c '-deps=/home/o3o/.dub/.redub/302574E9E172D1EA/302574E9E172D1EA.deps'
Failed after 6ms with message
	std.file.FileException@std/file.d(1000): /home/o3o/.dub/.redub/302574E9E172D1EA/obj/app.o: No such file or directory
-
```
## Environment:

 - redub version: 1.13.1
 - dub version: 1.38.1
 - OS: 16.11.5

**Comment by MrcSnm** [comment]
Regarding that issue, this is a wrong usage.

There's an error message here:

	**File was specified twice: File '/home/o3o/d/workshop/redub-issue/app.d' was specified in sourceFiles at directory '/home/o3o/d/workshop/redub-issue'. But it can already be found based on the current sourcePaths: ["/home/o3o/d/workshop/redub-issue"].  Either add this file to excludeSourceFiles or remove it from sourceFiles.**

That means you should remove from your .json

```json
"sourceFiles": [
		"app.d"
	],
```
With that, you're manually specifying app.d should be included in your build, and you can't include it twice, since it was found on the sourcePaths.


Also, I would recommend you to create a `source` folder, like how dub does. This is important to keep your cache controlled, since redub uses both directories and files for that

**Comment by o3o** [comment]
Thank you for the quick reply! 
It turns out this was my mistake. I had tried removing sourceFiles, but it still gave an error (most likely because I hadn’t used `--force`). 

Thanks again for this great project! In certain conditions, it’s even faster than reggae (with ninja). For example, compiling one of my projects (which uses Vibe.d) gives me these times:

 -  dub: 2.89s
 -  ninja: 1.91s
 -   redub: 0.86s!
