### ISSUE TITLE
Support redub -q test

### ISSUE THREAD

**Issue by nordlow** [MrcSnm/redub#29]
Currently 

```sh
redub -q test 
```

fails as 

```
Error Program exited with code 1
```

whereas 

```sh
dub -q test 
```

passes.

**Comment by nordlow** [comment]
Currently 

```sh
redub -q test 
```

fails as 

```
Error Program exited with code 1
```

whereas 

```sh
dub -q test 
```

passes.

**Comment by MrcSnm** [comment]
That happens due to how command line is handled inside redub, it uses D's std.getopt.

Old redub only supported `redub test -q`, now `redub -q test` is also valid.

**Comment by nordlow** [comment]
Awesome!
