### ISSUE TITLE
Allow using local compiler installation.

### ISSUE THREAD

**Issue by tgehr** [MrcSnm/redub#3]
`dub` can use a compiler executable from any directory, while `redub` can so far only handle global installs.

```bash
dub build --compiler=./ldc2-1.32.0-linux-x86_64/bin/ldc2
```

```bash
redub build --compiler=./ldc2-1.32.0-linux-x86_64/bin/ldc2
object.Error@(0): Unsupported compiler: ./ldc2-1.32.0-linux-x86_64/bin/ldc2
----------------
??:? immutable(char)[] building.cache.getCompilerVersion(immutable(char)[]) [0x5d2f9df8744f]
??:? immutable(char)[] building.cache.hashFrom(const(buildapi.BuildRequirements), immutable(char)[]) [0x5d2f9df87d69]
??:? building.cache.CompilationCache[] building.cache.cacheStatusForProject(buildapi.ProjectNode, immutable(char)[]) [0x5d2f9df87a66]
??:? void building.cache.invalidateCaches(buildapi.ProjectNode, immutable(char)[]) [0x5d2f9df87bcb]
??:? app.ProjectDetails app.resolveDependencies(immutable(char)[][]) [0x5d2f9df809d3]
??:? app.ProjectDetails app.buildBase(immutable(char)[][]) [0x5d2f9df80454]
??:? int app.buildMain(immutable(char)[][]) [0x5d2f9df8041c]
??:? _Dmain [0x5d2f9df7fe19
```

**Comment by MrcSnm** [comment]
Fixed at #2 e99f162

**Comment by tgehr** [comment]
Actually I think it does not work yet:

```
redub build --compiler=./ldc2-1.32.0-linux-x86_64/bin/ldc2
```
```
Failed after 3ms with message
	/bin/sh: 1: ./ldc2-1.32.0-linux-x86_64/bin/ldc2: not found
```

```
redub build --compiler=$PWD/ldc2-1.32.0-linux-x86_64/bin/ldc2
```
```
Linking Error
```

**Comment by MrcSnm** [comment]
Did you remember to do git pull and rebuild redub? If you did, this might be something related to linux. I have tested this feature under windows.

**Comment by tgehr** [comment]
Yes, I had rebuilt it. The linking error may be an unrelated issue, but it seems the current working directory is changed when building dependencies and therefore the relative path does not work.

**Comment by MrcSnm** [comment]
> Yes, I had rebuilt it. The linking error may be an unrelated issue, but it seems the current working directory is changed when building dependencies and therefore the relative path does not work.

Oh fine I guess I forgot to make it absolute, I'll fix that real quick

**Comment by MrcSnm** [comment]
Just done a second update on it, do try testing it :)
