### ISSUE TITLE
redub (test) doesn't propagate `versions` to compilation invocations

### ISSUE THREAD

**Issue by nordlow** [MrcSnm/redub#30]
For instance,

```sh
redub test
```

in

https://github.com/nordlow/yyjson-d

doesn't output any notifcation that unittests has been run in the output

```
Dependencies resolved - 8 ms "debug" using /home/per/.local/dlang/linux/bin64/dmd v2.110.0-beta.1-380-g50966e0232 [linux-x86_64] - no parallel
Copy Enough: yyjson-d; 
Up-to-Date: yyjson-d, skipping linking
Finished yyjson-d - 11223ms - To force a rebuild of up-to-date targets, run again with --force
```

.

*Update*: I just verified that the behavior is caused by `redub` not respecting

```
	versions "yyjson_test"
```

in unittest configuration.

This is an impotant feature to support because several large packages like the mir libraries conditionally enable their unittests using `version (PKG_tests)` qualified unittests to prevent those tests for being run when PKG .d files are imported by other libraries or applications that are compiled with -unittest flag. Note that opend supports selective running of unittests by having  `-unittest` take a set of modules as arguments.

. If I replace

```d
@safe pure nothrow @nogc version(yyjson_test) unittest {
```

with

```d
@safe pure nothrow @nogc unittest {
```

for a specific unittest `U` then `U` is run upon call to `redub test`.

**Comment by MrcSnm** [comment]
Redub does supper version in tests.

The problem is that it doesn't support `buildType` .

From what I've seen from your dub.sdl, there's also no reason to support it since what you have there can be achieved with `configurations` instead. e.g:

```json
"configurations": [
{
    "name": "unittest", 
    "versions": ["yyjson_test"],
    "dflags": [
        "-g", "-checkaction=context", "-allinst", "-unittest", "-cov", "-cov=ctfe",
        "-Xcc=-fuse-ld=lld"
    ],
    "dflags-posix-ldc": [
        "-fsanitize=address"
    ]
```

Then just call with redub test or `redub test -c unittest`

**Comment by MrcSnm** [comment]
Redub will now trigger an error message whenever buildType is being used

**Comment by nordlow** [comment]
Thank you!
