### ISSUE TITLE
--arch converted to --mtriple too directly?

### ISSUE THREAD

**Issue by p0nce** [MrcSnm/redub#9]
**How to reproduce**
Compiler Distort example/ in Dplug with `redub build --build=debug --arch=x86_64 --compiler=ldc2` => 
![image](https://github.com/MrcSnm/redub/assets/1067485/f314fde9-3a3b-46fd-ac19-c4122540b24a)

Repo here: https://github.com/AuburnSounds/Dplug/tree/master/examples/distort

DUB uses `-march=x86-64`, which works here.
Also works if triple is `--mtriple=x86_64-windows-msvc` is provided.
But redub provides `--mtriple=x86_64`, which doesn't seem correct.

**Comment by MrcSnm** [comment]
Fixed in 1.3.15
